kind: pipeline
type: docker

name: svelte components

steps:
  - name: install dependencies
    image: node:18-alpine
    commands:
      - npm install --include=dev

  - name: lint
    image: node:18-alpine
    commands:
      - npm run lint
    depends_on:
      - install dependencies

  - name: check
    image: node:18-alpine
    commands:
      - npm run check
    depends_on:
      - install dependencies

  - name: test-build
    image: node:18-alpine
    commands:
      - npm run package
    depends_on:
      - install dependencies

  - name: publish, if new version
    image: node:18-alpine
    environment:
      NPM_TOKEN:
        from_secret: NPM_TOKEN
    commands:
      - NAME=$(node -e 'console.log(JSON.parse(require("fs").readFileSync("package.json")).name)')
      - VERSION=$(node -e 'console.log(JSON.parse(require("fs").readFileSync("package.json")).version)')
      - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
      - (npm info "$NAME@$VERSION" >> /dev/null && echo "no new version" ) || (npm install --include=dev && npm run package && npm publish)
    depends_on:
      - install dependencies
      - lint
      - check
      - test-build
