kind: pipeline
type: docker

name: svelte components

steps:
  - name: lint-check-build
    image: node:18-alpine
    working_dir: frontend/
    commands:
      - npm install --include=dev
      - npm run lint
      - npm run check
      - npm run package

  - name: publish, if new version
    image: node:18-alpine
    commands:
      - NAME=$(node -e 'console.log(JSON.parse(require("fs").readFileSync("package.json")).name)')
      - VERSION=$(node -e 'console.log(JSON.parse(require("fs").readFileSync("package.json")).version)')
      - npm info "$NAME@$VERSION" || (npm install --include=dev && npm run package && npm publish)
    secrets: [NPM_TOKEN]
