kind: pipeline
type: docker

name: svelte components

steps:
  - name: install dependencies
    image: node:18-alpine
    commands:
      - npm install --include=dev

  - name: lint
    image: node:18-alpine
    commands:
      - npm run lint

  - name: check
    image: node:18-alpine
    commands:
      - npm run check

  - name: test-build
    image: node:18-alpine
    commands:
      - npm run package

  - name: publish, if new version
    image: node:18-alpine
    environment:
      NPM_TOKEN:
        from_secret: NPM_TOKEN
    commands:
      - NAME=$(node -e 'console.log(JSON.parse(require("fs").readFileSync("package.json")).name)')
      - VERSION=$(node -e 'console.log(JSON.parse(require("fs").readFileSync("package.json")).version)')
      - echo _auth=$NPM_TOKEN >> .npmrc
      - echo email="luca@it-rahn.de" >> .npmrc
      - echo always-auth=true >> .npmrc
      - (npm info "$NAME@$VERSION" >> /dev/null && echo "no new version" ) || (npm install --include=dev && npm run package && npm publish)
